### ISSUE TITLE
[bug] Glance App Widget Error

### ISSUE THREAD

**Issue by Quantenzitrone** [mhss1/MyBrain#114]
**Describe the bug**
The widgets are not working and just show the error:
> **Glance App Widget Error**
> Check the exact error using **`adb logcat`**, searching for **`GlanceAppWidget`**

So that's what I did:
```bash
$ adb logcat | grep GlanceAppWidget
11-02 15:44:26.997 18612 18647 W GlanceAppWidget: Cannot set the rounded corner of views before Api 31.
11-02 15:44:26.997 18612 18612 W GlanceAppWidget: Cannot set the rounded corner of views before Api 31.
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: Error in Glance App Widget
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Intent.writeToParcel(android.os.Parcel, int)' on a null object reference
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at android.widget.RemoteViews$SetOnClickFillInIntent.writeToParcel(RemoteViews.java:568)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at android.widget.RemoteViews.writeToParcel(RemoteViews.java:3817)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at android.os.Parcel.writeTypedArray(Parcel.java:1471)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.core.widget.RemoteViewsCompatService$RemoteViewsCompatServiceData$Companion$create$2.invoke(RemoteViewsCompatService.kt:36)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.core.widget.RemoteViewsCompatService$RemoteViewsCompatServiceData$Companion.serializeToBytes$core_remoteviews_release(RemoteViewsCompatService.kt:18)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.core.widget.RemoteViewsCompat.setRemoteAdapter(RemoteViewsCompat.kt:97)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateChild(RemoteViewsTranslator.kt:585)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.setChildren(RemoteViewsTranslator.kt:36)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateChild(RemoteViewsTranslator.kt:346)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.setChildren(RemoteViewsTranslator.kt:36)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateChild(RemoteViewsTranslator.kt:102)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateComposition(RemoteViewsTranslator.kt:370)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$composeForSize$2.invokeSuspend(GlanceAppWidget.kt:300)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$composeForSize$2.invoke(GlanceAppWidget.kt:13)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:72)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.composeForSize-AAqiGWc$glance_appwidget_release(GlanceAppWidget.kt:26)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.compose$glance_appwidget_release(GlanceAppWidget.kt:5)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.compose$glance_appwidget_release(GlanceAppWidget.kt:20)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$compose$1.invokeSuspend(Unknown Source:17)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-02 15:44:27.027 18612 18645 E GlanceAppWidget: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: Error in Glance App Widget
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Intent.writeToParcel(android.os.Parcel, int)' on a null object reference
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.widget.RemoteViews$SetOnClickFillInIntent.writeToParcel(RemoteViews.java:568)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.widget.RemoteViews.writeToParcel(RemoteViews.java:3817)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.os.Parcel.writeTypedArray(Parcel.java:1471)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.core.widget.RemoteViewsCompatService$RemoteViewsCompatServiceData$Companion$create$2.invoke(RemoteViewsCompatService.kt:36)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.core.widget.RemoteViewsCompatService$RemoteViewsCompatServiceData$Companion.serializeToBytes$core_remoteviews_release(RemoteViewsCompatService.kt:18)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.core.widget.RemoteViewsCompat.setRemoteAdapter(RemoteViewsCompat.kt:97)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateChild(RemoteViewsTranslator.kt:585)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.setChildren(RemoteViewsTranslator.kt:36)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateChild(RemoteViewsTranslator.kt:346)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.setChildren(RemoteViewsTranslator.kt:36)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateChild(RemoteViewsTranslator.kt:102)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.RemoteViewsTranslatorKt.translateComposition(RemoteViewsTranslator.kt:370)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$composeForSize$2.invokeSuspend(GlanceAppWidget.kt:300)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$composeForSize$2.invoke(GlanceAppWidget.kt:13)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:72)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.composeForSize-AAqiGWc$glance_appwidget_release(GlanceAppWidget.kt:26)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.compose$glance_appwidget_release(GlanceAppWidget.kt:5)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.compose$glance_appwidget_release(GlanceAppWidget.kt:20)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$update$4.invokeSuspend(GlanceAppWidget.kt:106)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget$update$4.invoke(GlanceAppWidget.kt:22)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.safeRun(GlanceAppWidget.kt:71)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at androidx.glance.appwidget.GlanceAppWidget.update(GlanceAppWidget.kt:34)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at com.mhss.app.mybrain.presentation.glance_widgets.TasksWidgetReceiver$observeData$1.invokeSuspend(TasksHomeWidget.kt:320)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.os.Handler.handleCallback(Handler.java:790)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.os.Looper.loop(Looper.java:164)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at android.app.ActivityThread.main(ActivityThread.java:6548)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-02 15:44:27.034 18612 18612 E GlanceAppWidget: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**To Reproduce**
1. Create a widget on your home screen.

**Smartphone:**
 - Device: SHIFT6m
 - OS: Android 8.1
 - App Version 1.0.3

**Comment by Quantenzitrone** [comment]
In the logs the same exact thing is happening twice, because I created both widgets, with both having the same problem...

**Comment by paulz1** [comment]
Same for me on another device.
Smartphone:

    Device: Moto G4
    OS: Android 8.1.0
    App Version 1.0.3

Just for additional info. I use Nova Launcher on my phone. But never seen any problem with widgets before.

**Comment by Quantenzitrone** [comment]
also on Android 8.1.0 interesting
i use Lawnchair 12 (the new Alpha one)

**Comment by mhss1** [comment]
It should be fixed in the next update

**Comment by mhss1** [comment]
If it still happens, it most likely because of the compose glance library itself

**Comment by paulz1** [comment]
Just for information.
Updating to 1.0.4 version and the problem is still there.
Could we do something about glance library ?

**Comment by mhss1** [comment]
I think I'll downgrade the version until they fix it
